"""Skeptic check 1 (independent of common.py / q21 / q22): figurate families mod 2^k and dropping classes.

Different code path from the researcher's scripts:
  * class labels are computed by iterating ALL residues mod 2^K at once with the working modulus
    shrinking by one bit per step (T^k(r) is well defined mod 2^(K-k));
  * N(k) is computed a second way, by a dynamic programme over admissible parity words;
  * triangular numbers are generated by cumulative sums, fibres are enumerated explicitly.

Conventions: shortcut map T(n) = n/2 | (q n + d)/2.  k = Terras stopping time (T-steps), class = residues
mod 2^k with coefficient stopping time exactly k (first k with q^s < 2^k).  Repo Set index = k + s.

Run: C:/repos/collatz/.venv/Scripts/python.exe -X utf8 v1_residues_classes.py
"""
import json
import os
import sys
import time

import numpy as np

HERE = os.path.dirname(os.path.abspath(__file__))
LOG = open(os.path.join(HERE, "v1_residues_classes.log"), "w", encoding="utf-8")
RES = {}
T0 = time.time()


def out(*a):
    s = " ".join(str(x) for x in a)
    print(s)
    LOG.write(s + "\n")
    LOG.flush()


# OEIS A100982, typed from https://oeis.org/A100982 (not from common.py)
A100982 = [1, 1, 2, 3, 7, 12, 30, 85, 173, 476, 961, 2652, 8045, 17637, 51033, 108950, 312455]
# OEIS A023105 (number of distinct quadratic residues mod 2^n, n >= 0)
A023105 = [1, 2, 2, 3, 4, 7, 12, 23, 44, 87, 172, 343, 684, 1367, 2732, 5463, 10924, 21847, 43692,
           87383, 174764, 349527, 699052, 1398103, 2796204]


def smax_table(K, q):
    """smax[k] = largest s with q^s < 2^k (exact integers)."""
    t = [0] * (K + 1)
    for k in range(1, K + 1):
        s = 0
        while q ** (s + 1) < (1 << k):
            s += 1
        t[k] = s
    return t


def class_labels(K, q=3, d=1):
    """lab[r] = coefficient stopping time of r mod 2^K (0 if > K), all residues at once."""
    M = 1 << K
    x = np.arange(M, dtype=np.int64)
    s = np.zeros(M, dtype=np.int64)
    lab = np.zeros(M, dtype=np.int64)
    alive = np.ones(M, dtype=bool)
    sm = smax_table(K, q)
    for k in range(1, K + 1):
        odd = (x & 1) == 1
        x = np.where(odd, (q * x + d) >> 1, x >> 1)
        x &= (1 << (K - k)) - 1            # T^k(r) is determined mod 2^(K-k) only
        s += odd
        drop = alive & (s <= sm[k])
        lab[drop] = k
        alive &= ~drop
    return lab


def N_by_dp(K, q=3):
    """N(k) = number of parity words of length k whose first drop (q^s < 2^j) is at j = k.
    Words <-> residues mod 2^k bijectively (Terras/Everett), for every odd q and d."""
    sm = smax_table(K, q)
    alive = {0: 1}          # s -> number of words of the current length that have not dropped
    N = {}
    for k in range(1, K + 1):
        new = {}
        for s, c in alive.items():
            for b in (0, 1):
                new[s + b] = new.get(s + b, 0) + c
        dropped = sum(c for s, c in new.items() if s <= sm[k])
        if dropped:
            N[k] = dropped
        alive = {s: c for s, c in new.items() if s > sm[k]}
    return N


# ---------------------------------------------------------------------------------------------
out("=" * 100)
out("A. Triangular numbers mod 2^k: CRS on [0,2^k), fibres, windows, negative indices")
out("=" * 100)
ok_crs = True
for k in range(0, 25):
    M = 1 << k
    t = np.cumsum(np.arange(M, dtype=np.int64)) & (M - 1)     # T_0..T_(M-1) by cumulative sums
    ok_crs &= (np.sort(t) == np.arange(M)).all()
out("  T_0..T_(2^k-1) is a CRS mod 2^k for k = 0..24 (cumsum generation):", bool(ok_crs))
ok_fib = True
for k in range(0, 14):
    M, M2 = 1 << k, 1 << (k + 1)
    fib = {}
    for n in range(M2):
        fib.setdefault((n * (n + 1) // 2) % M, []).append(n)
    ok_fib &= len(fib) == M and all(len(v) == 2 and v[0] + v[1] == M2 - 1 for v in fib.values())
out("  Z/2^(k+1) -> Z/2^k is onto, exactly 2-to-1, fibres {n, 2^(k+1)-1-n}, k = 0..13:", ok_fib)
# windows [a, a+2^k): CRS iff a = 0 mod 2^k  (so 'the first 2^k triangular numbers' must start at T_0)
ok_win = True
bad_example = None
for k in range(1, 10):
    M = 1 << k
    for a in range(-2 * M, 2 * M + 1):
        vals = {(n * (n + 1) // 2) % M for n in range(a, a + M)}
        is_crs = len(vals) == M
        if is_crs != (a % M == 0):
            ok_win = False
        if a == 1 and k == 3:
            bad_example = sorted((n * (n + 1) // 2) % M for n in range(1, M + 1))
out("  window [a, a+2^k) is a CRS mod 2^k  <=>  a = 0 mod 2^k   (k = 1..9, -2^(k+1) <= a <= 2^(k+1)):", ok_win)
out("     e.g. T_1..T_8 mod 8 =", bad_example, " (not a CRS: the count must start at T_0 = 0)")
ok_neg = all(((-1 - n) * (-n) // 2) == n * (n + 1) // 2 for n in range(-5000, 5000))
out("  T_(-1-n) = T_n for -5000 <= n < 5000:", ok_neg)
RES["A"] = dict(crs=bool(ok_crs), fibres=ok_fib, windows=ok_win, neg=ok_neg)

# ---------------------------------------------------------------------------------------------
out("")
out("=" * 100)
out("B. Class counts N(k): residue iteration (K = 20) versus word DP versus OEIS A100982")
out("=" * 100)
K = 20
lab31 = class_labels(K, 3, 1)
cnt = np.bincount(lab31, minlength=K + 1)
N_res = {k: int(cnt[k]) >> (K - k) for k in range(1, K + 1) if cnt[k]}
N_dp = N_by_dp(K, 3)
ks = sorted(N_res)
oe = [1] + A100982
ok_N = N_res == N_dp and [N_res[k] for k in ks] == oe[:len(ks)]
ok_div = all(int(cnt[k]) % (1 << (K - k)) == 0 for k in ks)
out("  k (A020914):", ks)
out("  N(k)       :", [N_res[k] for k in ks])
out("  residue count = DP count = [1] + A100982 :", ok_N, "  counts divisible by 2^(K-k):", ok_div)
out("  undetermined residues mod 2^20:", int(cnt[0]))
RES["B"] = dict(N={str(k): N_res[k] for k in ks}, ok=bool(ok_N))
# the class is a union of residue classes mod 2^k: lab constant on r mod 2^k
ok_union = True
for k in ks:
    sel = np.nonzero(lab31 == k)[0]
    base = np.unique(sel & ((1 << k) - 1))
    ok_union &= len(base) == N_res[k] and len(sel) == N_res[k] << (K - k)
out("  each class k is a union of exactly N(k) residue classes mod 2^k:", bool(ok_union))

# ---------------------------------------------------------------------------------------------
out("")
out("=" * 100)
out("C. Residue-level class counts along the families, one full period, for FIVE rules")
out("   'natural' means: counts equal (period / 2^K) * (natural counts) for EVERY class incl. undetermined")
out("   '#classes' = number of distinct determined classes (k <= K) met by the family")
out("=" * 100)
K = 16
M = 1 << K
n1 = np.arange(M, dtype=np.int64)            # one period for integer-coefficient polynomials
n2 = np.arange(2 * M, dtype=np.int64)        # one period for the families with a 1/2


def tri(n):
    return (n * (n + 1) // 2) % M


def poly(s):
    return lambda n: ((s - 2) * n * n - (s - 4) * n) // 2 % M


FAMS = {
    "T_n": (tri, n2, 2),
    "n^2": (lambda n: n * n % M, n1, 1),
    "n^3": (lambda n: (n * n % M) * n % M, n1, 1),
    "T_n^2": (lambda n: tri(n) * tri(n) % M, n2, 2),
    "pentagonal s=5": (poly(5), n2, 2),
    "hexagonal s=6": (poly(6), n1, 1),
    "octagonal s=8": (poly(8), n1, 1),
    "dodecagonal s=12": (poly(12), n1, 1),
}
RULES = [(3, 1), (3, -1), (5, 1), (5, -1), (7, 1)]
RES["C"] = {}
for (q, d) in RULES:
    lab = class_labels(K, q, d)
    nat = np.bincount(lab, minlength=K + 1)
    out(f"  rule {q}x{d:+d}:  classes k = {[k for k in range(1, K + 1) if nat[k]][:8]}...,"
        f" undetermined at K=16: {int(nat[0])} ({nat[0] / M:.4f})")
    row = {}
    for name, (f, dom, per) in FAMS.items():
        c = np.bincount(lab[f(dom)], minlength=K + 1)
        natural = bool((c == per * nat).all())
        ncl = int((c[1:] > 0).sum())
        top = sorted(((int(c[k]) / len(dom), k) for k in range(1, K + 1) if c[k]), reverse=True)[:4]
        row[name] = dict(natural=natural, n_classes=ncl, undetermined_share=float(c[0] / len(dom)))
        out(f"     {name:18s} natural: {natural!s:5s}  #classes met: {ncl:2d}   undetermined share {c[0] / len(dom):.4f}"
            f"   largest shares (share, k): {[(round(a, 4), k) for a, k in top]}")
    RES["C"][f"{q}x{d:+d}"] = row
out("  READ THIS: for 3x+1 the collapsed families (n^2, T_n^2, s = 0 mod 4) meet exactly 2 classes;")
out("  for 3x-1, 5x+-1, 7x+1 they do NOT: the two-class statement is rule- and sign-dependent.")

# why: which single residue class mod 4 / mod 8 is a dropping class for each rule
out("")
out("  the class of odd numbers that drops first, per rule (residues mod 2^k with k the 2nd Terras time):")
for (q, d) in RULES:
    lab = class_labels(8, q, d)
    kk = sorted(set(int(v) for v in lab if v))[1]
    rs = sorted(set(int(r) % (1 << kk) for r in np.nonzero(lab == kk)[0]))
    out(f"     {q}x{d:+d}: k = {kk}, residues mod 2^{kk}: {rs}   (odd squares are 1 mod 8)")

# ---------------------------------------------------------------------------------------------
out("")
out("=" * 100)
out("D. Actual integers, 3x+1: Terras stopping time of T_n, n^2, n^3, T_n^2 for 0 <= n < 2^21")
out("   (wider than the researcher's 2^20; pure Python integers)")
out("=" * 100)


def stop(n, q=3, d=1, cap=100000):
    x, k = n, 0
    while k < cap:
        x = (q * x + d) >> 1 if x & 1 else x >> 1
        k += 1
        if x < n:
            return k
    return None


KD = 21
LD = 1 << KD
N21 = N_by_dp(KD, 3)
RES["D"] = {}
for name, f in (("T_n", lambda n: n * (n + 1) // 2), ("n^2", lambda n: n * n),
                ("n^3", lambda n: n * n * n), ("T_n^2", lambda n: (n * (n + 1) // 2) ** 2)):
    h = {}
    nodrop = []
    for n in range(LD):
        k = stop(f(n))
        if k is None:
            nodrop.append(n)
        else:
            h[k] = h.get(k, 0) + 1
    if name in ("T_n", "n^3"):
        exact = all(h.get(k, 0) == (N21[k] << (KD - k)) - (1 if k in (1, 2) else 0) for k in N21)
        out(f"  {name:6s} non-dropping indices {nodrop};  count(k) = N(k) 2^(21-k) for all k <= 21"
            f" (minus the values 0, 1): {exact};  mass with k > 21: {sum(v for k, v in h.items() if k > KD)}")
        RES["D"][name] = dict(nodrop=nodrop, exact=exact)
    else:
        out(f"  {name:6s} non-dropping indices {nodrop};  histogram {dict(sorted(h.items()))}")
        RES["D"][name] = dict(nodrop=nodrop, hist={str(k): v for k, v in sorted(h.items())})

out("")
out("  Same families as seeds of the MIRROR map 3x-1 (actual integers, 2 <= n <= 200000):")
for name, f in (("n^2", lambda n: n * n), ("T_n^2", lambda n: (n * (n + 1) // 2) ** 2)):
    h = {}
    bad = 0
    for n in range(2, 200001):
        k = stop(f(n), 3, -1)
        if k is None:
            bad += 1
        else:
            h[k] = h.get(k, 0) + 1
    top = sorted(h.items(), key=lambda t: -t[1])[:8]
    out(f"  3x-1, {name:6s}: {len(h)} distinct stopping times, non-dropping {bad}; most common (k, count): {top}")
    RES["D"]["mirror " + name] = dict(distinct=len(h), top=top)

# ---------------------------------------------------------------------------------------------
out("")
out("=" * 100)
out("E. Squares and cubes mod 2^k")
out("=" * 100)
ok_sq = True
for k in range(0, 25):
    M_ = 1 << k
    x = np.arange(M_, dtype=np.int64)
    ok_sq &= len(np.unique(x * x & (M_ - 1))) == A023105[k]
    if k >= 1:
        ok_sq &= A023105[k] == ((1 << (k - 1)) + (4 if k % 2 == 0 else 5)) // 3
out("  #squares mod 2^k = A023105(k) = (2^(k-1)+4)/3 | (2^(k-1)+5)/3 for k = 0(1)..24:", bool(ok_sq))
ok_odd = True
for k in range(3, 21):
    M_ = 1 << k
    w = np.arange(1, M_, 2, dtype=np.int64)
    vals, mult = np.unique(w * w & (M_ - 1), return_counts=True)
    ok_odd &= (vals % 8 == 1).all() and len(vals) == M_ // 8 and (mult == 4).all()
out("  odd squares mod 2^k are exactly the residues 1 mod 8, each hit 4 times (k = 3..20):", bool(ok_odd))
# cubes: exhaustive isometry check on all pairs of odd residues mod 2^11
kk = 11
w = np.arange(1, 1 << kk, 2, dtype=np.int64)
A_, B_ = np.meshgrid(w, w)
D1 = (A_ - B_)
D3 = (A_ ** 3 - B_ ** 3)
mask = D1 != 0


def v2arr(z):
    z = np.abs(z)
    v = np.zeros(z.shape, dtype=np.int64)
    zz = z.copy()
    for _ in range(64):
        ev = (zz & 1) == 0
        ev &= zz != 0
        if not ev.any():
            break
        v += ev
        zz = np.where(ev, zz >> 1, zz)
    return v


ok_cube = bool((v2arr(D3[mask]) == v2arr(D1[mask])).all())
out("  v2(a^3 - b^3) = v2(a - b) for ALL pairs of distinct odd a, b < 2^11 (exhaustive):", ok_cube)
RES["E"] = dict(squares=bool(ok_sq), odd_squares=bool(ok_odd), cube_isometry=ok_cube)

out("")
out(f"done in {time.time() - T0:.1f} s")
with open(os.path.join(HERE, "v1_residues_classes.json"), "w", encoding="utf-8") as fh:
    json.dump(RES, fh, indent=1, default=str)
LOG.close()
