"""Verify the backward-propagation law of minimal strong-drop avoiders.

Claims under test (discovered in the A(n) table from three_bit_avoidance_tree):
 L1. If m = 1 mod 3 and m' = (4m-1)/3 is not strong (m' != 5 mod 16), then
     enc(m') = enc(m) + 1: prepending a weak drop extends any avoider.
 L2. If m = 2 mod 3 and m' = (8m-1)/3 is not strong, enc(m') = enc(m) + 1.
 L3. If m = 2 mod 3 and x = (2m-1)/3 > 1, then enc(x) = enc(m): prepending a
     growth step preserves the count (and SHRINKS the avoider by ~2/3!).
 L4. m = 0 mod 3 has no Syracuse preimage at all (family death).
 L5. A(n+1) is always obtainable from SOME n-avoider <= A(n+1) via L1-L3
     closure, i.e. the minimizer tree is generated by these three maps.

L3 is the sharp one: it means minimal avoiders are NOT monotone targets of
growth -- backward growth steps shrink. The minimum over a family is reached
by applying (2x-1)/3 as often as mod-3 gating allows.
"""

from __future__ import annotations

from three_bit_avoidance_tree import encounters_until_strong_py as enc


def is_strong(m: int) -> bool:
    return m % 16 == 5


def main() -> None:
    # L1/L2/L3 exhaustively for encounter values m <= 200001
    l1 = l2 = l3 = 0
    for m in range(5, 200002, 4):
        e = enc(m, max_enc=500)
        if m % 3 == 1:
            mp = (4 * m - 1) // 3
            assert mp % 4 == 1
            if not is_strong(mp):
                assert enc(mp, 500) == e + 1, (m, mp)
                l1 += 1
        if m % 3 == 2:
            mp = (8 * m - 1) // 3
            if mp % 4 == 1 and not is_strong(mp):
                assert enc(mp, 500) == e + 1, (m, mp)
                l2 += 1
            x = (2 * m - 1) // 3
            if x > 1:
                assert enc(x, 500) == e, (m, x)
                l3 += 1
    print(f"L1 weak-preimage law:   {l1} cases, 0 violations")
    print(f"L2 medium-preimage law: {l2} cases, 0 violations")
    print(f"L3 growth-preimage law: {l3} cases, 0 violations")

    # Where does (8m-1)/3 land mod 4? It is not always an encounter value.
    bad = sum(1 for m in range(5, 20002, 4) if m % 3 == 2 and ((8 * m - 1) // 3) % 4 != 1)
    print(f"L2 note: (8m-1)/3 fails to be an encounter (3 mod 4) in {bad} of "
          f"{sum(1 for m in range(5, 20002, 4) if m % 3 == 2)} eligible cases")

    # L4: multiples of 3 have no preimage (algebraic, just demonstrate)
    print("L4: 2^d * m = 1 (mod 3) is unsolvable for m = 0 (mod 3) -- algebraic")


if __name__ == "__main__":
    main()
