"""Q3.4 side checks quoted in the README (dead ends and one-line facts), logged so that they can be re-run.

  (a) P_p(x, theta) at integer theta: factor degrees of det(x - R_e - theta R_o)/(x - 1 - theta) for ten primes and
      theta in {1, -1, 2, -2, 3, -3, 5}: reducible only at theta = +-1.
  (b) p = 37: does any non-trivial affine map x -> alpha x + beta preserve a sporadic eigenspace (+1, -1, or their sum;
      functions or measures)?  All 36*37 - 1 = 1331 maps are tried.
  (c) the 'dual' kernel d -> 1/d: (1/2)(x -> 2x) + (1/2)(x -> 3x + 1) (the semigroup generated by 2x and 3x+1)
      against the Terras kernel and its transpose, primes 7, 11, 13, 31, 37.
  (d) p = 37: compressions of R_e and R_o to the sporadic eigenspaces.

Run:  python -X utf8 q34d_side_checks.py      (writes q34d_side_checks.log)
"""
from __future__ import annotations

import sys
import time
from pathlib import Path

import numpy as np
import sympy as sp

sys.path.insert(0, str(Path(__file__).resolve().parent))
from gk_common import branches, charpoly_int, pdivmod, two_K  # noqa: E402

T0 = time.time()
LOG: list[str] = []
x = sp.symbols("x")


def say(s: str = "") -> None:
    print(s, flush=True)
    LOG.append(s)


# ------------------------------------------------------------------------------- (a)
say("=== (a) factor degrees of P_p(x, theta) at integer theta ===")
for p in (5, 7, 11, 13, 23, 29, 31, 37, 41, 43):
    e, o = branches(p)
    out = []
    for th in (1, -1, 2, -2, 3, -3, 5):
        A = np.zeros((p, p), dtype=np.int64)
        for t in range(p):
            A[t, e[t]] += 1
            A[t, o[t]] += th
        cp = charpoly_int(A, radius=1 + abs(th))
        q, r = pdivmod(cp, [-(1 + th), 1])
        assert r == [0]
        fl = sp.Poly(q[::-1], x).factor_list()[1]
        out.append((th, sorted((f.degree(), m) for f, m in fl)))
    irr = all(len(d) == 1 and d[0][1] == 1 for th, d in out if abs(th) > 1)
    say(f"   p = {p:>2}: irreducible at theta = 2, -2, 3, -3, 5: {irr};  theta = 1: {out[0][1]};  theta = -1: {out[1][1]}")

# ------------------------------------------------------------------------------- (b)
say("\n=== (b) p = 37: affine maps preserving a sporadic eigenspace ===")
p = 37
A = sp.Matrix(two_K(p).tolist())
I = sp.eye(p)
spaces = {}
for lam in (1, -1):
    spaces[("functions", lam)] = sp.Matrix.hstack(*(A - lam * I).nullspace())
    spaces[("measures", lam)] = sp.Matrix.hstack(*(A.T - lam * I).nullspace())
spaces[("functions", "+-1")] = sp.Matrix.hstack(spaces[("functions", 1)], spaces[("functions", -1)])
spaces[("measures", "+-1")] = sp.Matrix.hstack(spaces[("measures", 1)], spaces[("measures", -1)])
BIG = 16777213


def rank_mod(M: np.ndarray, m: int) -> int:
    B = (M % m).astype(np.int64)
    r = 0
    for c in range(B.shape[1]):
        piv = np.nonzero(B[r:, c])[0]
        if len(piv) == 0:
            continue
        i = r + int(piv[0])
        if i != r:
            B[[r, i]] = B[[i, r]]
        B[r] = (B[r] * pow(int(B[r, c]), -1, m)) % m
        col = B[:, c].copy()
        col[r] = 0
        nz = np.nonzero(col)[0]
        if len(nz):
            B[nz] = (B[nz] - np.outer(col[nz], B[r])) % m
        r += 1
        if r == B.shape[0]:
            break
    return r


for key, Bs in spaces.items():
    # clear denominators, work modulo a 24-bit prime (rank mod r <= rank over Q, so 'not preserved mod r' needs care:
    # preserved over Q  =>  rank[B | RB] = rank B over Q  =>  rank mod r <= rank B; we report maps with rank mod r <= rank B)
    den = sp.ilcm(*[sp.Rational(c).q for c in Bs])
    Bi = np.array((Bs * den).tolist(), dtype=object)
    Bn = np.array([[int(v) % BIG for v in row] for row in Bi], dtype=np.int64)
    rk = rank_mod(Bn, BIG)
    hits = []
    for al in range(1, p):
        for be in range(p):
            if al == 1 and be == 0:
                continue
            perm = [(al * t + be) % p for t in range(p)]
            if rank_mod(np.hstack([Bn, Bn[perm, :]]), BIG) <= rk:
                hits.append((al, be))
    say(f"   {key}: dimension {Bs.shape[1]}; affine maps (of 1331) that could preserve it: {hits}")

# ------------------------------------------------------------------------------- (c)
say("\n=== (c) Terras kernel (multipliers 1/2, 3/2) against the kernel of the semigroup <2x, 3x+1> (multipliers 2, 3) ===")


def kern_ab(p: int, a: int, b: int) -> np.ndarray:
    M = np.zeros((p, p), dtype=np.int64)
    for t in range(p):
        M[t, a * t % p] += 1
        M[t, (b * t + 1) % p] += 1
    return M


def fac(M: np.ndarray):
    cp = charpoly_int(M)
    q, r = pdivmod(cp, [-2, 1])
    fl = sp.Poly(q[::-1], x).factor_list()[1]
    return sorted((str(f.as_expr()) if f.degree() <= 2 else f"deg{f.degree()}", m) for f, m in fl), q


for p in (7, 11, 13, 31, 37):
    i2 = pow(2, -1, p)
    f1, q1 = fac(kern_ab(p, i2, 3 * i2 % p))
    f2, q2 = fac(kern_ab(p, 2, 3))
    f3, q3 = fac(kern_ab(p, 2, 2 * pow(3, -1, p) % p))
    say(f"   p = {p:>2}: Terras {f1}")
    say(f"           semigroup <2x, 3x+1> {f2};  same polynomial as Terras: {q1 == q2};  transpose of Terras equals Terras: {q1 == q3}")

# ------------------------------------------------------------------------------- (d)
say("\n=== (d) p = 37: compressions of R_e, R_o to the sporadic eigenspaces ===")
e, o = branches(p)
Re = sp.zeros(p, p)
Ro = sp.zeros(p, p)
for t in range(p):
    Re[t, e[t]] = 1
    Ro[t, o[t]] = 1
for lam in (1, -1):
    R = spaces[("functions", lam)]
    L = spaces[("measures", lam)]
    G = L.T * R
    Ce = G.inv() * (L.T * Re * R)
    Co = G.inv() * (L.T * Ro * R)
    say(f"   eigenvalue {lam:+d}: charpoly of compressed R_e: {sp.Poly(Ce.charpoly(x).as_expr(), x).clear_denoms()[1].as_expr()};  of compressed R_o: {sp.Poly(Co.charpoly(x).as_expr(), x).clear_denoms()[1].as_expr()}")
say(f"total time {time.time() - T0:.0f} s")
Path(__file__).with_suffix(".log").write_text("\n".join(LOG) + "\n", encoding="utf-8")
